### PR TITLE
json-view

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pavithirakc** [comment]
Getting the follow error while rendering the templates of releaseseries and release. What could be the reason?
`TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'wadllib.iso_strptime.TimeZone'>, ())`

**Comment by loechel** [comment]
Pavi, sorry for the late response.

I have tried to debug those, but it is a pickle / unpickle error, that is due to schema modifications. 

You have to start over with a new plone portal.

**Comment by ghost** [comment]
In all places, where release.title is referred to, it raises the following error:

`TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'wadllib.iso_strptime.TimeZone'>, ())`

what could be the reason?

**Comment by ghost** [comment]
on running /hotfix_json from hotfixfolder, I am getting a BadRequest error:
```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 72, in mapply
  Module ZPublisher.Publish, line 53, in missing_name
  Module ZPublisher.HTTPResponse, line 741, in badRequestError
BadRequest:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Invalid request</strong></p>

  The parameter, <em>context</em>, was omitted from the request.<p>Make sure to specify all required parameters, and try the request again.</p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

```
what could be the reason?

**Comment by loechel** [comment]
you have defined that the call method needs a context as param, which will not be provided, I have fixed that.

**Comment by ghost** [comment]
on running /hotfix_json from hotfixfolder,
I am getting 
`TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'wadllib.iso_strptime.TimeZone'>, ())`
I referred to your commit for fixing the same  error before- the date_released field was typecast into DateTime.
 But the current error is pointing at the following line:
`key=lambda version: parse_version(version[0].title)`
what could be the fix?

**Comment by loechel** [comment]
sorry, I did try to reproduce, but never see this error, I did instead get an error because of the missing file field (hotfix) in hotfixes, that resulted from the copy of most code from plone.app.vulnerabilities. https://github.com/plone/ploneorg.releasesecurityinfo/blob/json-view/src/ploneorg/releasesecurityinfo/browser/views.py#L137-L142 could not work with current schema.

Maybe you have modified code, so please check in and I will try again to reproduce

**Comment by ghost** [comment]
I've pushed the changes. removed the file fields in hotfix and I think download_url and pypi_name should still work. I am still getting the same error though, could be some problem with my setup.

**Review by loechel — APPROVED** [review]

**Pull request merged**
